language: scala

scala:
  - 2.11.7

jdk:
  - oraclejdk8
  - openjdk7

script:
  - sbt ++$TRAVIS_SCALA_VERSION 'test-only * -- exclude slow'

notifications:
  webhooks:
    urls: 
      - https://webhooks.gitter.im/e/8250f89d1d4c140f0a11
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
